### ISSUE TITLE
Future request

### ISSUE THREAD

**Issue by NguyenASang** [0xkuj/3DAppVersionSpoofer#1]
Can you add a way to change the app version in settings instead of 3D Touch? I'm using an old device so I don't have 3D Touch, thank you for your work.

**Comment by 0xkuj** [comment]
I think you can use Force3DAppshortcuts  or Peek-a-boo from repo.ioscreatix.com to enable 3d menu for older devices. anyway ill add support for settings once ill get to that

**Comment by NguyenASang** [comment]
I prefer the change in Settings, hope you can add it soon. Also, does the tweak's code work on iOS 12?

**Comment by 0xkuj** [comment]
added option in settings as well as support for iOS below 13
