### ISSUE TITLE
Wallet and Apple Pay not working

### ISSUE THREAD

**Issue by hervay** [0xkuj/3DAppVersionSpoofer#14]
After installing the tweak, i got a loads of crash reports from cr4shed (passd). It didn't respring during the crashes, but i was unable to use apple pay or open the wallet app.
After disabling the tweak injection in iCleaner, everything works normal.

**Comment by 0xkuj** [comment]
This doesn't sound related at all. This tweak won't inject itself into daemons such as passd or anything not app related.. After you disabled it and everything was fine, did you try enabling it again?
Also, what iOS, iPhone and jailbreak do you have?

**Comment by hervay** [comment]
Looks like you're right. Enabled it and everything works fine. Sorry for opening a thread for this, I was suspicious because I installed the tweak a day ago, and this kind of crash never happened before. (Also not installed any other tweaks for months so I thought it should be this one)

Anyway, thanks for your quick reply, and sorry for the inconvenience!

Have a nice day!

**Comment by 0xkuj** [comment]
If you have like an old iOS, it could be just a jetsam issue. There are tweaks that fixes that I forgot the name but it contains the word "jetsam" look it up
np
