### ISSUE TITLE
Fake version doesn't work with Spotify

### ISSUE THREAD

**Issue by NguyenASang** [0xkuj/3DAppVersionSpoofer#2]
**Watch this video**

https://user-images.githubusercontent.com/87893636/182006835-7628f9a5-12ab-47cb-9eab-780bea9ddef0.MP4

**Information**
Device: iPhone 6
iOS: 12.5.5
Jailbreak: Chimera

**Comment by 0xkuj** [comment]
This doesn't necessarily means it is not working. what are you trying to achieve with spotify version spoof? the app is working as intended

**Comment by NguyenASang** [comment]
@0xkuj I'm trying to get the new UI of Spotify without update to the latest version.

**Comment by 0xkuj** [comment]
this is not what the tweak suppose to do. 
it will spoof the version number of an app as a fake version number, to confuse the app to think it has a different version. no UI changes will be made obviously.
