### ISSUE TITLE
Fake version not working with Google Voice

### ISSUE THREAD

**Issue by shadowscott** [0xkuj/3DAppVersionSpoofer#5]
Currently have older version installed (22.25) because I am not on iOS 14, but it still gives me prompt saying I need to update 
![image](https://user-images.githubusercontent.com/21198582/206860454-c48d422a-ff61-4e07-90ac-73f9d61059be.png)

**Comment by 0xkuj** [comment]
as it was said, this tweak will not support all apps as different apps have different ways to verify your version number.
